[project]
name = "api"
version = "0.1.0"
description = "FastAPI Backend"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi",
    "uvicorn",
    "pydantic",
    "supabase",
    "pandas",
    "pdfplumber",
    "python-multipart"
]

[tool.setuptools]
packages = ["api"]
